SPY:
  asset_class: equity
  currency: USD
  tick_size: 0.01
  contract_multiplier: 1
  trading_cost_bps: 1.0

EURUSD:
  asset_class: fx
  currency: USD 
  tick_size: 0.001
  contract_multiplier: 1
  trading_cost_bps: 0.5